version: '3.8'

services:
  frontend:
    # Используем Dockerfile из текущей директории
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ts_frontend_app

    # Сопоставление портов:
    # "ВНЕШНИЙ_ПОРТ:ВНУТРЕННИЙ_ПОРТ_КОНТЕЙНЕРА"
    # Теперь внешний порт 8080 направляется на порт 80 Nginx внутри контейнера.
    ports:
      - "8080:80"
